compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU        #
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: fp16  # Use 'bf16' if your hardware supports it
num_machines: 1
num_processes: 4  # Adjust this based on the number of GPUs you wish to utilize
use_cpu: false
enable_cpu_affinity: true